import PDFDocument from 'pdfkit';

/** Maps documentType slugs to their human-readable display labels. */
const DOCUMENT_TYPE_LABELS: Record<string, string> = {
  'business-ideas': 'Business Ideas',
  'business-plan': 'Business Plan',
  'marketing-plan': 'Marketing Plan',
  'product-proposal': 'Product / Sales Proposal',
};

/**
 * Generates a branded A4 PDF from plain text business document content.
 *
 * Produces a single PDF with a Hadafi-branded header banner, document metadata,
 * a separator line, the full document body, and a per-page footer with page
 * numbers. Requires `bufferPages: true` so footer page-range logic works.
 *
 * @param documentType - One of the DOCUMENT_TYPE_LABELS keys (e.g. 'business-plan').
 * @param title        - Document title displayed in the header and footer.
 * @param content      - Plain-text body of the document.
 * @returns A Buffer containing the complete PDF binary.
 */
export async function generateBusinessDocumentPdf(
  documentType: string,
  title: string,
  content: string,
): Promise<Buffer> {
  const label = DOCUMENT_TYPE_LABELS[documentType] ?? 'Business Document';

  // bufferPages: true is required for doc.bufferedPageRange() used in the footer loop.
  const doc = new PDFDocument({ margin: 50, size: 'A4', bufferPages: true });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk: Buffer) => chunks.push(chunk));

  await new Promise<void>((resolve, reject) => {
    doc.on('end', resolve);
    doc.on('error', reject);

    // ── Header banner ─────────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 80).fill('#9f2063');
    doc.fillColor('white').fontSize(22).font('Helvetica-Bold')
       .text(label, 50, 20);
    doc.fillColor('rgba(255,255,255,0.85)').fontSize(13).font('Helvetica')
       .text(title || label, 50, 52);

    // ── Meta info ─────────────────────────────────────────────────────────────
    doc.moveDown(3);
    doc.fillColor('#6b7280').fontSize(11).font('Helvetica')
       .text('Generated by Hadafi AI Business Assistant — potential.com');
    doc.moveDown(0.5);
    doc.fillColor('#9CA3AF').fontSize(10)
       .text(
         new Date().toLocaleDateString('en-GB', {
           year: 'numeric',
           month: 'long',
           day: 'numeric',
         }),
       );
    doc.moveDown(2);

    // ── Separator line ────────────────────────────────────────────────────────
    doc.moveTo(50, doc.y)
       .lineTo(doc.page.width - 50, doc.y)
       .strokeColor('#f7e8f0')
       .lineWidth(1)
       .stroke();
    doc.moveDown(1.5);

    // ── Document content ──────────────────────────────────────────────────────
    doc.fillColor('#1f2937').fontSize(12).font('Helvetica')
       .text(content, {
         lineGap: 4,
         paragraphGap: 8,
         align: 'left',
       });

    // ── Footer on every page ──────────────────────────────────────────────────
    // Must be called after all content is written so page count is final.
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
      doc.switchToPage(range.start + i);
      const oldBottom = doc.page.margins.bottom;
      doc.page.margins.bottom = 0;
      doc.fillColor('#9CA3AF').fontSize(9).font('Helvetica')
         .text(
           `Generated with Hadafi AI Business Assistant — potential.com    ·    Page ${i + 1} of ${range.count}`,
           50,
           doc.page.height - 30,
           { align: 'center', width: doc.page.width - 100 },
         );
      doc.page.margins.bottom = oldBottom;
    }

    doc.end();
  });

  return Buffer.concat(chunks);
}
